name: Call Reusable Workflow With Environments

on:
  workflow_dispatch:
    inputs:
      nome:
        description: "Digite seu nome"
        required: true
        default: "Genivaldo"
jobs:
  deploy-dev:
    uses: SEU-USUARIO/gh-reusable-workflows/.github/workflows/hello-reusable.yml@main
    with:
      environment_git: dev
      nome: Genivaldo
      app_url: ${{ vars.DEV_APP_URL }}
    secrets:
      token_app: ${{ secrets.DEV_TOKEN_APP }}

  deploy-hml:
    needs: deploy-dev
    uses: SEU-USUARIO/gh-reusable-workflows/.github/workflows/hello-reusable.yml@main
    with:
      environment_git: hml
      nome: Genivaldo
      app_url: ${{ vars.HML_APP_URL }}
    secrets:
      token_app: ${{ secrets.HML_TOKEN_APP }}
