name: Call Reusable Workflow With Environments

on:
  workflow_dispatch:
    inputs:
      nome:
        description: "Digite seu nome"
        required: true
        default: "Genivaldo"

jobs:
  dev:
    name: Executar DEV
    environment: dev
    uses: geni-junior/gh-reusable-workflows/.github/workflows/hello-reusable.yml@main
    with:
      nome: ${{ inputs.nome }}
      ambiente: dev
      app_url: ${{ vars.APP_URL }}
    secrets:
      token_app: ${{ secrets.TOKEN_APP }}

  hml:
    name: Executar HML
    needs: dev
    environment: hml
    uses: geni-junior/gh-reusable-workflows/.github/workflows/hello-reusable.yml@main
    with:
      nome: ${{ inputs.nome }}
      ambiente: hml
      app_url: ${{ vars.APP_URL }}
    secrets:
      token_app: ${{ secrets.TOKEN_APP }}
